docx_processing_task:
  description: >
    Process DOCX files and convert their content into Markdown format for further analysis.
  expected_output: >
    A Markdown file containing the extracted content from the DOCX document.
  agent: docx_processor

csv_processing_task:
  description: >
    Process CSV files and convert their data into Markdown tables for analysis and reporting.
  expected_output: >
    A Markdown table representing the data from the CSV file.
  agent: csv_processor

pdf_processing_task:
  description: >
    Extract and convert PDF content into Markdown format for analysis.
  expected_output: >
    A Markdown file containing the extracted content from the PDF document.
  agent: pdf_processor

image_processing_task:
  description: >
    Extract text from images (e.g., JPG, PNG) using OCR and format it into Markdown.
  expected_output: >
    A Markdown file containing the extracted text from the image.
  agent: image_processor

excel_processing_task:
  description: >
    Convert Excel spreadsheets into Markdown tables for further use.
  expected_output: >
    A Markdown table representing the data from the Excel spreadsheet.
  agent: xlsx_processor
